//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AskerTracker.Properties {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("AskerTracker.Domain.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string ABNegative {
            get {
                return ResourceManager.GetString("ABNegative", resourceCulture);
            }
        }
        
        public static string ABPositive {
            get {
                return ResourceManager.GetString("ABPositive", resourceCulture);
            }
        }
        
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        public static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        public static string AmountOutOfRange {
            get {
                return ResourceManager.GetString("AmountOutOfRange", resourceCulture);
            }
        }
        
        public static string AmountRequired {
            get {
                return ResourceManager.GetString("AmountRequired", resourceCulture);
            }
        }
        
        public static string ANegative {
            get {
                return ResourceManager.GetString("ANegative", resourceCulture);
            }
        }
        
        public static string APositive {
            get {
                return ResourceManager.GetString("APositive", resourceCulture);
            }
        }
        
        public static string BirthDate {
            get {
                return ResourceManager.GetString("BirthDate", resourceCulture);
            }
        }
        
        public static string BloodType {
            get {
                return ResourceManager.GetString("BloodType", resourceCulture);
            }
        }
        
        public static string BNegative {
            get {
                return ResourceManager.GetString("BNegative", resourceCulture);
            }
        }
        
        public static string BPositive {
            get {
                return ResourceManager.GetString("BPositive", resourceCulture);
            }
        }
        
        public static string Camping {
            get {
                return ResourceManager.GetString("Camping", resourceCulture);
            }
        }
        
        public static string Combat {
            get {
                return ResourceManager.GetString("Combat", resourceCulture);
            }
        }
        
        public static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        public static string Cooperation {
            get {
                return ResourceManager.GetString("Cooperation", resourceCulture);
            }
        }
        
        public static string DateHeld {
            get {
                return ResourceManager.GetString("DateHeld", resourceCulture);
            }
        }
        
        public static string DateJoined {
            get {
                return ResourceManager.GetString("DateJoined", resourceCulture);
            }
        }
        
        public static string DateLeft {
            get {
                return ResourceManager.GetString("DateLeft", resourceCulture);
            }
        }
        
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        public static string Event {
            get {
                return ResourceManager.GetString("Event", resourceCulture);
            }
        }
        
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        public static string HandReleasePushup {
            get {
                return ResourceManager.GetString("HandReleasePushup", resourceCulture);
            }
        }
        
        public static string Hiking {
            get {
                return ResourceManager.GetString("Hiking", resourceCulture);
            }
        }
        
        public static string Internal {
            get {
                return ResourceManager.GetString("Internal", resourceCulture);
            }
        }
        
        public static string IsTeamProperty {
            get {
                return ResourceManager.GetString("IsTeamProperty", resourceCulture);
            }
        }
        
        public static string JMBG {
            get {
                return ResourceManager.GetString("JMBG", resourceCulture);
            }
        }
        
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        public static string LegTuck {
            get {
                return ResourceManager.GetString("LegTuck", resourceCulture);
            }
        }
        
        public static string Lender {
            get {
                return ResourceManager.GetString("Lender", resourceCulture);
            }
        }
        
        public static string LenderId {
            get {
                return ResourceManager.GetString("LenderId", resourceCulture);
            }
        }
        
        public static string Length3to1000 {
            get {
                return ResourceManager.GetString("Length3to1000", resourceCulture);
            }
        }
        
        public static string Length3to15 {
            get {
                return ResourceManager.GetString("Length3to15", resourceCulture);
            }
        }
        
        public static string Length3to20 {
            get {
                return ResourceManager.GetString("Length3to20", resourceCulture);
            }
        }
        
        public static string Length3to200 {
            get {
                return ResourceManager.GetString("Length3to200", resourceCulture);
            }
        }
        
        public static string Length3to40 {
            get {
                return ResourceManager.GetString("Length3to40", resourceCulture);
            }
        }
        
        public static string Length3to50 {
            get {
                return ResourceManager.GetString("Length3to50", resourceCulture);
            }
        }
        
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        public static string Match {
            get {
                return ResourceManager.GetString("Match", resourceCulture);
            }
        }
        
        public static string MaximumDeadliftWeight {
            get {
                return ResourceManager.GetString("MaximumDeadliftWeight", resourceCulture);
            }
        }
        
        public static string Member {
            get {
                return ResourceManager.GetString("Member", resourceCulture);
            }
        }
        
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        public static string NameRequired {
            get {
                return ResourceManager.GetString("NameRequired", resourceCulture);
            }
        }
        
        public static string Nickname {
            get {
                return ResourceManager.GetString("Nickname", resourceCulture);
            }
        }
        
        public static string ONegative {
            get {
                return ResourceManager.GetString("ONegative", resourceCulture);
            }
        }
        
        public static string OPositive {
            get {
                return ResourceManager.GetString("OPositive", resourceCulture);
            }
        }
        
        public static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        public static string Owner {
            get {
                return ResourceManager.GetString("Owner", resourceCulture);
            }
        }
        
        public static string OwnerId {
            get {
                return ResourceManager.GetString("OwnerId", resourceCulture);
            }
        }
        
        public static string OwnershipChange {
            get {
                return ResourceManager.GetString("OwnershipChange", resourceCulture);
            }
        }
        
        public static string Participants {
            get {
                return ResourceManager.GetString("Participants", resourceCulture);
            }
        }
        
        public static string PersonalIdMinLengthIs13 {
            get {
                return ResourceManager.GetString("PersonalIdMinLengthIs13", resourceCulture);
            }
        }
        
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        public static string SprintDragCarry {
            get {
                return ResourceManager.GetString("SprintDragCarry", resourceCulture);
            }
        }
        
        public static string StandingPowerThrow {
            get {
                return ResourceManager.GetString("StandingPowerThrow", resourceCulture);
            }
        }
        
        public static string TeamPropertyRequired {
            get {
                return ResourceManager.GetString("TeamPropertyRequired", resourceCulture);
            }
        }
        
        public static string Testing {
            get {
                return ResourceManager.GetString("Testing", resourceCulture);
            }
        }
        
        public static string TotalScore {
            get {
                return ResourceManager.GetString("TotalScore", resourceCulture);
            }
        }
        
        public static string Trainings {
            get {
                return ResourceManager.GetString("Trainings", resourceCulture);
            }
        }
        
        public static string TrainingType {
            get {
                return ResourceManager.GetString("TrainingType", resourceCulture);
            }
        }
        
        public static string TransactionDate {
            get {
                return ResourceManager.GetString("TransactionDate", resourceCulture);
            }
        }
        
        public static string TwoMileRun {
            get {
                return ResourceManager.GetString("TwoMileRun", resourceCulture);
            }
        }
        
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        public static string WeakestDisciplinePoints {
            get {
                return ResourceManager.GetString("WeakestDisciplinePoints", resourceCulture);
            }
        }
    }
}
