//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AskerTracker.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AskerTracker.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AB-.
        /// </summary>
        public static string ABNegative {
            get {
                return ResourceManager.GetString("ABNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AB+.
        /// </summary>
        public static string ABPositive {
            get {
                return ResourceManager.GetString("ABPositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount is out of range.
        /// </summary>
        public static string AmountOutOfRange {
            get {
                return ResourceManager.GetString("AmountOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount is required.
        /// </summary>
        public static string AmountRequired {
            get {
                return ResourceManager.GetString("AmountRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A-.
        /// </summary>
        public static string ANegative {
            get {
                return ResourceManager.GetString("ANegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A+.
        /// </summary>
        public static string APositive {
            get {
                return ResourceManager.GetString("APositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of birth.
        /// </summary>
        public static string BirthDate {
            get {
                return ResourceManager.GetString("BirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blood type.
        /// </summary>
        public static string BloodType {
            get {
                return ResourceManager.GetString("BloodType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B-.
        /// </summary>
        public static string BNegative {
            get {
                return ResourceManager.GetString("BNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B+.
        /// </summary>
        public static string BPositive {
            get {
                return ResourceManager.GetString("BPositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camping.
        /// </summary>
        public static string Camping {
            get {
                return ResourceManager.GetString("Camping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combat.
        /// </summary>
        public static string Combat {
            get {
                return ResourceManager.GetString("Combat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cooperation.
        /// </summary>
        public static string Cooperation {
            get {
                return ResourceManager.GetString("Cooperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date held.
        /// </summary>
        public static string DateHeld {
            get {
                return ResourceManager.GetString("DateHeld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date joined.
        /// </summary>
        public static string DateJoined {
            get {
                return ResourceManager.GetString("DateJoined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date left.
        /// </summary>
        public static string DateLeft {
            get {
                return ResourceManager.GetString("DateLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event.
        /// </summary>
        public static string Event {
            get {
                return ResourceManager.GetString("Event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full name.
        /// </summary>
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hand Release Pushup.
        /// </summary>
        public static string HandReleasePushup {
            get {
                return ResourceManager.GetString("HandReleasePushup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiking.
        /// </summary>
        public static string Hiking {
            get {
                return ResourceManager.GetString("Hiking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal.
        /// </summary>
        public static string Internal {
            get {
                return ResourceManager.GetString("Internal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team property.
        /// </summary>
        public static string IsTeamProperty {
            get {
                return ResourceManager.GetString("IsTeamProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JMBG.
        /// </summary>
        public static string JMBG {
            get {
                return ResourceManager.GetString("JMBG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leg Tuck.
        /// </summary>
        public static string LegTuck {
            get {
                return ResourceManager.GetString("LegTuck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lender.
        /// </summary>
        public static string Lender {
            get {
                return ResourceManager.GetString("Lender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lender ID.
        /// </summary>
        public static string LenderId {
            get {
                return ResourceManager.GetString("LenderId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length out of range (3 - 1000).
        /// </summary>
        public static string Length3to1000 {
            get {
                return ResourceManager.GetString("Length3to1000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length out of range (3 - 15).
        /// </summary>
        public static string Length3to15 {
            get {
                return ResourceManager.GetString("Length3to15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length out of range (3 - 20).
        /// </summary>
        public static string Length3to20 {
            get {
                return ResourceManager.GetString("Length3to20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length out of range (3 - 200).
        /// </summary>
        public static string Length3to200 {
            get {
                return ResourceManager.GetString("Length3to200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length out of range (3 - 40).
        /// </summary>
        public static string Length3to40 {
            get {
                return ResourceManager.GetString("Length3to40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length out of range (3 - 50).
        /// </summary>
        public static string Length3to50 {
            get {
                return ResourceManager.GetString("Length3to50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match.
        /// </summary>
        public static string Match {
            get {
                return ResourceManager.GetString("Match", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum Deadlift Weight.
        /// </summary>
        public static string MaximumDeadliftWeight {
            get {
                return ResourceManager.GetString("MaximumDeadliftWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member.
        /// </summary>
        public static string Member {
            get {
                return ResourceManager.GetString("Member", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is required.
        /// </summary>
        public static string NameRequired {
            get {
                return ResourceManager.GetString("NameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nickname.
        /// </summary>
        public static string Nickname {
            get {
                return ResourceManager.GetString("Nickname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0-.
        /// </summary>
        public static string ONegative {
            get {
                return ResourceManager.GetString("ONegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0+.
        /// </summary>
        public static string OPositive {
            get {
                return ResourceManager.GetString("OPositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner.
        /// </summary>
        public static string Owner {
            get {
                return ResourceManager.GetString("Owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner ID.
        /// </summary>
        public static string OwnerId {
            get {
                return ResourceManager.GetString("OwnerId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ownership changed.
        /// </summary>
        public static string OwnershipChange {
            get {
                return ResourceManager.GetString("OwnershipChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Participants.
        /// </summary>
        public static string Participants {
            get {
                return ResourceManager.GetString("Participants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal ID length is 13.
        /// </summary>
        public static string PersonalIdMinLengthIs13 {
            get {
                return ResourceManager.GetString("PersonalIdMinLengthIs13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PhoneNumber.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprint Drag Carry.
        /// </summary>
        public static string SprintDragCarry {
            get {
                return ResourceManager.GetString("SprintDragCarry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standing Power Throw.
        /// </summary>
        public static string StandingPowerThrow {
            get {
                return ResourceManager.GetString("StandingPowerThrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team property (true/false) required.
        /// </summary>
        public static string TeamPropertyRequired {
            get {
                return ResourceManager.GetString("TeamPropertyRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testing.
        /// </summary>
        public static string Testing {
            get {
                return ResourceManager.GetString("Testing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total score.
        /// </summary>
        public static string TotalScore {
            get {
                return ResourceManager.GetString("TotalScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trainings.
        /// </summary>
        public static string Trainings {
            get {
                return ResourceManager.GetString("Trainings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training type.
        /// </summary>
        public static string TrainingType {
            get {
                return ResourceManager.GetString("TrainingType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction date.
        /// </summary>
        public static string TransactionDate {
            get {
                return ResourceManager.GetString("TransactionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two Mile Run.
        /// </summary>
        public static string TwoMileRun {
            get {
                return ResourceManager.GetString("TwoMileRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number.
        /// </summary>
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weakest Discipline Points.
        /// </summary>
        public static string WeakestDisciplinePoints {
            get {
                return ResourceManager.GetString("WeakestDisciplinePoints", resourceCulture);
            }
        }
    }
}
