version: "2"
services:
    mssql:
      image: "mcr.microsoft.com/mssql/server:2019-latest"
      ports:
        - "1433:1433"
      networks:
        - asnet
    web:
      build: .
      depends_on:
        - mssql
      networks:
        - asnet

networks:
  asnet:
    name: nat